import type { Database, Json } from "@/src/lib/supabase/types";

type PayrollConceptInsert = Database["public"]["Tables"]["payroll_concepts"]["Insert"];
type LegalParameterInsert = Database["public"]["Tables"]["legal_parameters"]["Insert"];
type LegalParameterVersionInsert =
  Database["public"]["Tables"]["legal_parameter_versions"]["Insert"];
type PositionInsert = Database["public"]["Tables"]["positions"]["Insert"];
type DepartmentInsert = Database["public"]["Tables"]["departments"]["Insert"];

export const DEFAULT_PAYROLL_SETTINGS = {
  country_code: "CO",
  payroll_frequency: "quincenal",
  overtime_enabled: true,
  social_security_enabled: true,
  parafiscals_enabled: true,
  benefits_enabled: true,
  transport_allowance_enabled: true,
  daytime_start: "06:00",
  daytime_end: "21:00",
  night_start: "21:00",
  weekly_max_hours: 46,
} as const;

export const DEFAULT_POSITIONS: Omit<PositionInsert, "company_id">[] = [
  {
    code: "ADMIN",
    name: "Administrador",
    description: "Personal administrativo y de manejo.",
    config: {
      allows_overtime: false,
      allows_night_surcharge: true,
      allows_sunday: true,
    },
  },
  {
    code: "COCINA_JEFE",
    name: "Jefe de cocina",
    description: "Responsable de producción y coordinación de cocina.",
    config: { allows_overtime: true },
  },
  {
    code: "COCINA_AUX",
    name: "Auxiliar de cocina",
    description: "Apoyo operativo de cocina.",
    config: { allows_overtime: true },
  },
  {
    code: "ANFITRIONA",
    name: "Anfitriona",
    description: "Servicio al cliente y operación de salón.",
    config: { allows_overtime: true },
  },
  {
    code: "CAJA",
    name: "Caja",
    description: "Operación de caja y recaudo.",
    config: { allows_overtime: true },
  },
];

export const DEFAULT_DEPARTMENTS: Omit<DepartmentInsert, "company_id">[] = [
  {
    code: "ADM",
    name: "Administración",
    description: "Operación administrativa, RRHH y soporte.",
    config: {},
  },
  {
    code: "COC",
    name: "Cocina",
    description: "Producción y apoyo de cocina.",
    config: {},
  },
  {
    code: "SAL",
    name: "Servicio",
    description: "Caja, anfitrionas y experiencia del cliente.",
    config: {},
  },
  {
    code: "DIG",
    name: "Canales digitales",
    description: "Ventas online y operación digital.",
    config: {},
  },
];

type ConceptSeed = Omit<PayrollConceptInsert, "company_id">;

export const DEFAULT_PAYROLL_CONCEPTS: ConceptSeed[] = [
  {
    code: "SALARIO_BASICO",
    name: "Salario básico",
    category: "ingresos_salariales",
    subcategory: "basico",
    type: "earning",
    is_active: true,
    is_base_concept: true,
    is_editable: false,
    is_deletable: false,
    salary_constitutive: true,
    affects_health_ibc: true,
    affects_pension_ibc: true,
    affects_arl_ibc: true,
    affects_parafiscals: true,
    affects_severance: true,
    affects_severance_interest: true,
    affects_service_bonus: true,
    affects_vacation_base: true,
    requires_days: false,
    requires_hours: false,
    requires_amount: true,
    auto_calculated: true,
    formula_type: "salary_base",
    formula_config: {},
    priority: 10,
    rounding_mode: "half_up",
    applies_by_default: true,
  },
  {
    code: "HED",
    name: "Horas extras diurnas",
    category: "ingresos_salariales",
    subcategory: "horas_extras",
    type: "earning",
    is_active: true,
    is_base_concept: true,
    is_editable: true,
    is_deletable: false,
    salary_constitutive: true,
    affects_health_ibc: true,
    affects_pension_ibc: true,
    affects_arl_ibc: true,
    affects_parafiscals: true,
    affects_severance: true,
    affects_severance_interest: true,
    affects_service_bonus: true,
    affects_vacation_base: true,
    requires_days: false,
    requires_hours: true,
    requires_amount: true,
    auto_calculated: true,
    formula_type: "overtime_day",
    formula_config: {},
    priority: 20,
    rounding_mode: "half_up",
    applies_by_default: true,
  },
  {
    code: "HEN",
    name: "Horas extras nocturnas",
    category: "ingresos_salariales",
    subcategory: "horas_extras",
    type: "earning",
    is_active: true,
    is_base_concept: true,
    is_editable: true,
    is_deletable: false,
    salary_constitutive: true,
    affects_health_ibc: true,
    affects_pension_ibc: true,
    affects_arl_ibc: true,
    affects_parafiscals: true,
    affects_severance: true,
    affects_severance_interest: true,
    affects_service_bonus: true,
    affects_vacation_base: true,
    requires_days: false,
    requires_hours: true,
    requires_amount: true,
    auto_calculated: true,
    formula_type: "overtime_night",
    formula_config: {},
    priority: 21,
    rounding_mode: "half_up",
    applies_by_default: true,
  },
  {
    code: "RN",
    name: "Recargo nocturno",
    category: "ingresos_salariales",
    subcategory: "recargos",
    type: "earning",
    is_active: true,
    is_base_concept: true,
    is_editable: true,
    is_deletable: false,
    salary_constitutive: true,
    affects_health_ibc: true,
    affects_pension_ibc: true,
    affects_arl_ibc: true,
    affects_parafiscals: true,
    affects_severance: true,
    affects_severance_interest: true,
    affects_service_bonus: true,
    affects_vacation_base: true,
    requires_days: false,
    requires_hours: true,
    requires_amount: true,
    auto_calculated: true,
    formula_type: "night_surcharge",
    formula_config: {},
    priority: 22,
    rounding_mode: "half_up",
    applies_by_default: true,
  },
  {
    code: "DOMFEST",
    name: "Dominical o festivo",
    category: "ingresos_salariales",
    subcategory: "recargos",
    type: "earning",
    is_active: true,
    is_base_concept: true,
    is_editable: true,
    is_deletable: false,
    salary_constitutive: true,
    affects_health_ibc: true,
    affects_pension_ibc: true,
    affects_arl_ibc: true,
    affects_parafiscals: true,
    affects_severance: true,
    affects_severance_interest: true,
    affects_service_bonus: true,
    affects_vacation_base: true,
    requires_days: false,
    requires_hours: true,
    requires_amount: true,
    auto_calculated: true,
    formula_type: "sunday_surcharge",
    formula_config: {},
    priority: 23,
    rounding_mode: "half_up",
    applies_by_default: true,
  },
  {
    code: "HEDDF",
    name: "Hora extra diurna dominical/festiva",
    category: "ingresos_salariales",
    subcategory: "horas_extras",
    type: "earning",
    is_active: true,
    is_base_concept: true,
    is_editable: true,
    is_deletable: false,
    salary_constitutive: true,
    affects_health_ibc: true,
    affects_pension_ibc: true,
    affects_arl_ibc: true,
    affects_parafiscals: true,
    affects_severance: true,
    affects_severance_interest: true,
    affects_service_bonus: true,
    affects_vacation_base: true,
    requires_days: false,
    requires_hours: true,
    requires_amount: true,
    auto_calculated: true,
    formula_type: "overtime_sunday_day",
    formula_config: {},
    priority: 24,
    rounding_mode: "half_up",
    applies_by_default: true,
  },
  {
    code: "HENDF",
    name: "Hora extra nocturna dominical/festiva",
    category: "ingresos_salariales",
    subcategory: "horas_extras",
    type: "earning",
    is_active: true,
    is_base_concept: true,
    is_editable: true,
    is_deletable: false,
    salary_constitutive: true,
    affects_health_ibc: true,
    affects_pension_ibc: true,
    affects_arl_ibc: true,
    affects_parafiscals: true,
    affects_severance: true,
    affects_severance_interest: true,
    affects_service_bonus: true,
    affects_vacation_base: true,
    requires_days: false,
    requires_hours: true,
    requires_amount: true,
    auto_calculated: true,
    formula_type: "overtime_sunday_night",
    formula_config: {},
    priority: 25,
    rounding_mode: "half_up",
    applies_by_default: true,
  },
  {
    code: "AUX_TRANSPORTE",
    name: "Auxilio de transporte",
    category: "ingresos_no_salariales",
    subcategory: "auxilios",
    type: "earning",
    is_active: true,
    is_base_concept: true,
    is_editable: true,
    is_deletable: false,
    salary_constitutive: false,
    affects_health_ibc: false,
    affects_pension_ibc: false,
    affects_arl_ibc: false,
    affects_parafiscals: false,
    affects_severance: false,
    affects_severance_interest: false,
    affects_service_bonus: false,
    affects_vacation_base: false,
    requires_days: false,
    requires_hours: false,
    requires_amount: true,
    auto_calculated: true,
    formula_type: "transport_allowance",
    formula_config: {},
    priority: 30,
    rounding_mode: "half_up",
    applies_by_default: true,
  },
  {
    code: "BONO_SALARIAL",
    name: "Bonificaciones salariales",
    category: "ingresos_salariales",
    subcategory: "bonificaciones",
    type: "earning",
    is_active: true,
    is_base_concept: false,
    is_editable: true,
    is_deletable: true,
    salary_constitutive: true,
    affects_health_ibc: true,
    affects_pension_ibc: true,
    affects_arl_ibc: true,
    affects_parafiscals: true,
    affects_severance: true,
    affects_severance_interest: true,
    affects_service_bonus: true,
    affects_vacation_base: true,
    requires_days: false,
    requires_hours: false,
    requires_amount: true,
    auto_calculated: false,
    formula_type: "manual",
    formula_config: {},
    priority: 35,
    rounding_mode: "half_up",
    applies_by_default: true,
  },
  {
    code: "COMISION",
    name: "Comisiones",
    category: "ingresos_salariales",
    subcategory: "comisiones",
    type: "earning",
    is_active: true,
    is_base_concept: false,
    is_editable: true,
    is_deletable: true,
    salary_constitutive: true,
    affects_health_ibc: true,
    affects_pension_ibc: true,
    affects_arl_ibc: true,
    affects_parafiscals: true,
    affects_severance: true,
    affects_severance_interest: true,
    affects_service_bonus: true,
    affects_vacation_base: true,
    requires_days: false,
    requires_hours: false,
    requires_amount: true,
    auto_calculated: false,
    formula_type: "manual",
    formula_config: {},
    priority: 36,
    rounding_mode: "half_up",
    applies_by_default: true,
  },
  {
    code: "SALUD_EMPLEADO",
    name: "Salud empleado",
    category: "descuentos_empleado",
    subcategory: "seguridad_social",
    type: "deduction",
    is_active: true,
    is_base_concept: true,
    is_editable: false,
    is_deletable: false,
    salary_constitutive: false,
    affects_health_ibc: false,
    affects_pension_ibc: false,
    affects_arl_ibc: false,
    affects_parafiscals: false,
    affects_severance: false,
    affects_severance_interest: false,
    affects_service_bonus: false,
    affects_vacation_base: false,
    requires_days: false,
    requires_hours: false,
    requires_amount: true,
    auto_calculated: true,
    formula_type: "health_employee",
    formula_config: {},
    priority: 100,
    rounding_mode: "half_up",
    applies_by_default: true,
  },
  {
    code: "PENSION_EMPLEADO",
    name: "Pensión empleado",
    category: "descuentos_empleado",
    subcategory: "seguridad_social",
    type: "deduction",
    is_active: true,
    is_base_concept: true,
    is_editable: false,
    is_deletable: false,
    salary_constitutive: false,
    affects_health_ibc: false,
    affects_pension_ibc: false,
    affects_arl_ibc: false,
    affects_parafiscals: false,
    affects_severance: false,
    affects_severance_interest: false,
    affects_service_bonus: false,
    affects_vacation_base: false,
    requires_days: false,
    requires_hours: false,
    requires_amount: true,
    auto_calculated: true,
    formula_type: "pension_employee",
    formula_config: {},
    priority: 101,
    rounding_mode: "half_up",
    applies_by_default: true,
  },
  {
    code: "FSP",
    name: "Fondo de solidaridad pensional",
    category: "descuentos_empleado",
    subcategory: "seguridad_social",
    type: "deduction",
    is_active: true,
    is_base_concept: true,
    is_editable: true,
    is_deletable: false,
    salary_constitutive: false,
    affects_health_ibc: false,
    affects_pension_ibc: false,
    affects_arl_ibc: false,
    affects_parafiscals: false,
    affects_severance: false,
    affects_severance_interest: false,
    affects_service_bonus: false,
    affects_vacation_base: false,
    requires_days: false,
    requires_hours: false,
    requires_amount: true,
    auto_calculated: true,
    formula_type: "solidarity_fund",
    formula_config: {},
    priority: 102,
    rounding_mode: "half_up",
    applies_by_default: true,
  },
  {
    code: "SALUD_EMPRESA",
    name: "Salud empleador",
    category: "aportes_empresa",
    subcategory: "seguridad_social",
    type: "employer_contribution",
    is_active: true,
    is_base_concept: true,
    is_editable: false,
    is_deletable: false,
    salary_constitutive: false,
    affects_health_ibc: false,
    affects_pension_ibc: false,
    affects_arl_ibc: false,
    affects_parafiscals: false,
    affects_severance: false,
    affects_severance_interest: false,
    affects_service_bonus: false,
    affects_vacation_base: false,
    requires_days: false,
    requires_hours: false,
    requires_amount: true,
    auto_calculated: true,
    formula_type: "health_employer",
    formula_config: {},
    priority: 110,
    rounding_mode: "half_up",
    applies_by_default: true,
  },
  {
    code: "PENSION_EMPRESA",
    name: "Pensión empleador",
    category: "aportes_empresa",
    subcategory: "seguridad_social",
    type: "employer_contribution",
    is_active: true,
    is_base_concept: true,
    is_editable: false,
    is_deletable: false,
    salary_constitutive: false,
    affects_health_ibc: false,
    affects_pension_ibc: false,
    affects_arl_ibc: false,
    affects_parafiscals: false,
    affects_severance: false,
    affects_severance_interest: false,
    affects_service_bonus: false,
    affects_vacation_base: false,
    requires_days: false,
    requires_hours: false,
    requires_amount: true,
    auto_calculated: true,
    formula_type: "pension_employer",
    formula_config: {},
    priority: 111,
    rounding_mode: "half_up",
    applies_by_default: true,
  },
  {
    code: "ARL",
    name: "ARL",
    category: "aportes_empresa",
    subcategory: "seguridad_social",
    type: "employer_contribution",
    is_active: true,
    is_base_concept: true,
    is_editable: true,
    is_deletable: false,
    salary_constitutive: false,
    affects_health_ibc: false,
    affects_pension_ibc: false,
    affects_arl_ibc: false,
    affects_parafiscals: false,
    affects_severance: false,
    affects_severance_interest: false,
    affects_service_bonus: false,
    affects_vacation_base: false,
    requires_days: false,
    requires_hours: false,
    requires_amount: true,
    auto_calculated: true,
    formula_type: "arl",
    formula_config: {},
    priority: 112,
    rounding_mode: "half_up",
    applies_by_default: true,
  },
  {
    code: "CAJA_COMPENSACION",
    name: "Caja de compensación",
    category: "aportes_empresa",
    subcategory: "parafiscales",
    type: "employer_contribution",
    is_active: true,
    is_base_concept: true,
    is_editable: false,
    is_deletable: false,
    salary_constitutive: false,
    affects_health_ibc: false,
    affects_pension_ibc: false,
    affects_arl_ibc: false,
    affects_parafiscals: false,
    affects_severance: false,
    affects_severance_interest: false,
    affects_service_bonus: false,
    affects_vacation_base: false,
    requires_days: false,
    requires_hours: false,
    requires_amount: true,
    auto_calculated: true,
    formula_type: "caja_compensacion",
    formula_config: {},
    priority: 120,
    rounding_mode: "half_up",
    applies_by_default: true,
  },
  {
    code: "ICBF",
    name: "ICBF",
    category: "aportes_empresa",
    subcategory: "parafiscales",
    type: "employer_contribution",
    is_active: true,
    is_base_concept: true,
    is_editable: false,
    is_deletable: false,
    salary_constitutive: false,
    affects_health_ibc: false,
    affects_pension_ibc: false,
    affects_arl_ibc: false,
    affects_parafiscals: false,
    affects_severance: false,
    affects_severance_interest: false,
    affects_service_bonus: false,
    affects_vacation_base: false,
    requires_days: false,
    requires_hours: false,
    requires_amount: true,
    auto_calculated: true,
    formula_type: "icbf",
    formula_config: {},
    priority: 121,
    rounding_mode: "half_up",
    applies_by_default: true,
  },
  {
    code: "SENA",
    name: "SENA",
    category: "aportes_empresa",
    subcategory: "parafiscales",
    type: "employer_contribution",
    is_active: true,
    is_base_concept: true,
    is_editable: false,
    is_deletable: false,
    salary_constitutive: false,
    affects_health_ibc: false,
    affects_pension_ibc: false,
    affects_arl_ibc: false,
    affects_parafiscals: false,
    affects_severance: false,
    affects_severance_interest: false,
    affects_service_bonus: false,
    affects_vacation_base: false,
    requires_days: false,
    requires_hours: false,
    requires_amount: true,
    auto_calculated: true,
    formula_type: "sena",
    formula_config: {},
    priority: 122,
    rounding_mode: "half_up",
    applies_by_default: true,
  },
  {
    code: "CESANTIAS",
    name: "Cesantías",
    category: "prestaciones",
    subcategory: "prestaciones_sociales",
    type: "provision",
    is_active: true,
    is_base_concept: true,
    is_editable: false,
    is_deletable: false,
    salary_constitutive: false,
    affects_health_ibc: false,
    affects_pension_ibc: false,
    affects_arl_ibc: false,
    affects_parafiscals: false,
    affects_severance: false,
    affects_severance_interest: false,
    affects_service_bonus: false,
    affects_vacation_base: false,
    requires_days: false,
    requires_hours: false,
    requires_amount: true,
    auto_calculated: true,
    formula_type: "severance",
    formula_config: {},
    priority: 130,
    rounding_mode: "half_up",
    applies_by_default: true,
  },
  {
    code: "INT_CESANTIAS",
    name: "Intereses de cesantías",
    category: "prestaciones",
    subcategory: "prestaciones_sociales",
    type: "provision",
    is_active: true,
    is_base_concept: true,
    is_editable: false,
    is_deletable: false,
    salary_constitutive: false,
    affects_health_ibc: false,
    affects_pension_ibc: false,
    affects_arl_ibc: false,
    affects_parafiscals: false,
    affects_severance: false,
    affects_severance_interest: false,
    affects_service_bonus: false,
    affects_vacation_base: false,
    requires_days: false,
    requires_hours: false,
    requires_amount: true,
    auto_calculated: true,
    formula_type: "severance_interest",
    formula_config: {},
    priority: 131,
    rounding_mode: "half_up",
    applies_by_default: true,
  },
  {
    code: "PRIMA",
    name: "Prima de servicios",
    category: "prestaciones",
    subcategory: "prestaciones_sociales",
    type: "provision",
    is_active: true,
    is_base_concept: true,
    is_editable: false,
    is_deletable: false,
    salary_constitutive: false,
    affects_health_ibc: false,
    affects_pension_ibc: false,
    affects_arl_ibc: false,
    affects_parafiscals: false,
    affects_severance: false,
    affects_severance_interest: false,
    affects_service_bonus: false,
    affects_vacation_base: false,
    requires_days: false,
    requires_hours: false,
    requires_amount: true,
    auto_calculated: true,
    formula_type: "service_bonus",
    formula_config: {},
    priority: 132,
    rounding_mode: "half_up",
    applies_by_default: true,
  },
  {
    code: "VAC_CAUSADAS",
    name: "Vacaciones causadas",
    category: "prestaciones",
    subcategory: "vacaciones",
    type: "provision",
    is_active: true,
    is_base_concept: true,
    is_editable: false,
    is_deletable: false,
    salary_constitutive: false,
    affects_health_ibc: false,
    affects_pension_ibc: false,
    affects_arl_ibc: false,
    affects_parafiscals: false,
    affects_severance: false,
    affects_severance_interest: false,
    affects_service_bonus: false,
    affects_vacation_base: false,
    requires_days: false,
    requires_hours: false,
    requires_amount: true,
    auto_calculated: true,
    formula_type: "vacation_accrual",
    formula_config: {},
    priority: 133,
    rounding_mode: "half_up",
    applies_by_default: true,
  },
  {
    code: "INCAP_EG",
    name: "Incapacidad enfermedad general",
    category: "novedades",
    subcategory: "incapacidades",
    type: "novelty",
    is_active: true,
    is_base_concept: true,
    is_editable: true,
    is_deletable: false,
    salary_constitutive: true,
    affects_health_ibc: true,
    affects_pension_ibc: true,
    affects_arl_ibc: true,
    affects_parafiscals: true,
    affects_severance: true,
    affects_severance_interest: true,
    affects_service_bonus: true,
    affects_vacation_base: true,
    requires_days: true,
    requires_hours: false,
    requires_amount: true,
    auto_calculated: false,
    formula_type: "manual",
    formula_config: { recommended_percentage: 0.6667 },
    priority: 200,
    rounding_mode: "half_up",
    applies_by_default: true,
  },
  {
    code: "FALTA_J",
    name: "Falta justificada",
    category: "novedades",
    subcategory: "faltas",
    type: "novelty",
    is_active: true,
    is_base_concept: true,
    is_editable: true,
    is_deletable: false,
    salary_constitutive: false,
    affects_health_ibc: false,
    affects_pension_ibc: false,
    affects_arl_ibc: false,
    affects_parafiscals: false,
    affects_severance: false,
    affects_severance_interest: false,
    affects_service_bonus: false,
    affects_vacation_base: false,
    requires_days: true,
    requires_hours: false,
    requires_amount: true,
    auto_calculated: false,
    formula_type: "manual",
    formula_config: {},
    priority: 201,
    rounding_mode: "half_up",
    applies_by_default: true,
  },
  {
    code: "FALTA_NJ",
    name: "Falta no justificada",
    category: "novedades",
    subcategory: "faltas",
    type: "deduction",
    is_active: true,
    is_base_concept: true,
    is_editable: true,
    is_deletable: false,
    salary_constitutive: false,
    affects_health_ibc: false,
    affects_pension_ibc: false,
    affects_arl_ibc: false,
    affects_parafiscals: false,
    affects_severance: false,
    affects_severance_interest: false,
    affects_service_bonus: false,
    affects_vacation_base: false,
    requires_days: true,
    requires_hours: false,
    requires_amount: true,
    auto_calculated: false,
    formula_type: "manual",
    formula_config: {},
    priority: 202,
    rounding_mode: "half_up",
    applies_by_default: true,
  },
];

type LegalSeed = {
  parameter: Omit<LegalParameterInsert, "company_id">;
  versions: Omit<LegalParameterVersionInsert, "company_id" | "legal_parameter_id">[];
};

export const DEFAULT_LEGAL_PARAMETERS: LegalSeed[] = [
  {
    parameter: {
      key: "salario_minimo",
      name: "Salario mínimo legal mensual vigente",
      description: "Valor base salarial por vigencia.",
      value_type: "number",
      is_global: true,
      can_company_override: true,
    },
    versions: [{ value: { amount: 1423500 }, version_label: "2026", valid_from: "2026-01-01" }],
  },
  {
    parameter: {
      key: "auxilio_transporte",
      name: "Auxilio de transporte",
      description: "Auxilio mensual aplicable por vigencia.",
      value_type: "number",
      is_global: true,
      can_company_override: true,
    },
    versions: [{ value: { amount: 200000 }, version_label: "2026", valid_from: "2026-01-01" }],
  },
  {
    parameter: {
      key: "salud_empleado",
      name: "Salud empleado",
      description: "Porcentaje descontado al empleado.",
      value_type: "percentage",
      is_global: true,
      can_company_override: true,
    },
    versions: [{ value: { rate: 0.04 }, version_label: "2026", valid_from: "2026-01-01" }],
  },
  {
    parameter: {
      key: "salud_empleador",
      name: "Salud empleador",
      description: "Porcentaje aportado por la empresa.",
      value_type: "percentage",
      is_global: true,
      can_company_override: true,
    },
    versions: [{ value: { rate: 0.085 }, version_label: "2026", valid_from: "2026-01-01" }],
  },
  {
    parameter: {
      key: "pension_empleado",
      name: "Pensión empleado",
      description: "Porcentaje descontado al empleado.",
      value_type: "percentage",
      is_global: true,
      can_company_override: true,
    },
    versions: [{ value: { rate: 0.04 }, version_label: "2026", valid_from: "2026-01-01" }],
  },
  {
    parameter: {
      key: "pension_empleador",
      name: "Pensión empleador",
      description: "Porcentaje aportado por la empresa.",
      value_type: "percentage",
      is_global: true,
      can_company_override: true,
    },
    versions: [{ value: { rate: 0.12 }, version_label: "2026", valid_from: "2026-01-01" }],
  },
  {
    parameter: {
      key: "fondo_solidaridad",
      name: "Fondo de solidaridad pensional",
      description: "Aporte adicional por topes altos de IBC.",
      value_type: "json",
      is_global: true,
      can_company_override: true,
    },
    versions: [
      {
        value: { threshold_in_smlv: 4, rate: 0.01 },
        version_label: "2026",
        valid_from: "2026-01-01",
      },
    ],
  },
  {
    parameter: {
      key: "arl_risk_classes",
      name: "ARL por clase de riesgo",
      description: "Tarifa por clase de riesgo.",
      value_type: "json",
      is_global: true,
      can_company_override: true,
    },
    versions: [
      {
        value: {
          class_1: 0.00522,
          class_2: 0.01044,
          class_3: 0.02436,
          class_4: 0.0435,
          class_5: 0.0696,
        },
        version_label: "2026",
        valid_from: "2026-01-01",
      },
    ],
  },
  {
    parameter: {
      key: "caja_compensacion",
      name: "Caja de compensación",
      description: "Porcentaje parafiscal.",
      value_type: "percentage",
      is_global: true,
      can_company_override: true,
    },
    versions: [{ value: { rate: 0.04 }, version_label: "2026", valid_from: "2026-01-01" }],
  },
  {
    parameter: {
      key: "icbf",
      name: "ICBF",
      description: "Porcentaje parafiscal.",
      value_type: "percentage",
      is_global: true,
      can_company_override: true,
    },
    versions: [{ value: { rate: 0.03 }, version_label: "2026", valid_from: "2026-01-01" }],
  },
  {
    parameter: {
      key: "sena",
      name: "SENA",
      description: "Porcentaje parafiscal.",
      value_type: "percentage",
      is_global: true,
      can_company_override: true,
    },
    versions: [{ value: { rate: 0.02 }, version_label: "2026", valid_from: "2026-01-01" }],
  },
  {
    parameter: {
      key: "recargo_nocturno",
      name: "Recargo nocturno",
      description: "Multiplicador incremental.",
      value_type: "percentage",
      is_global: true,
      can_company_override: true,
    },
    versions: [{ value: { rate: 0.35 }, version_label: "2026", valid_from: "2026-01-01" }],
  },
  {
    parameter: {
      key: "hora_extra_diurna",
      name: "Hora extra diurna",
      description: "Multiplicador total de pago.",
      value_type: "percentage",
      is_global: true,
      can_company_override: true,
    },
    versions: [{ value: { rate: 1.25 }, version_label: "2026", valid_from: "2026-01-01" }],
  },
  {
    parameter: {
      key: "hora_extra_nocturna",
      name: "Hora extra nocturna",
      description: "Multiplicador total de pago.",
      value_type: "percentage",
      is_global: true,
      can_company_override: true,
    },
    versions: [{ value: { rate: 1.75 }, version_label: "2026", valid_from: "2026-01-01" }],
  },
  {
    parameter: {
      key: "dominical_festivo",
      name: "Dominical o festivo",
      description: "Recargo dominical o festivo vigente.",
      value_type: "percentage",
      is_global: true,
      can_company_override: true,
    },
    versions: [
      { value: { rate: 0.8 }, version_label: "2026", valid_from: "2026-01-01" },
      { value: { rate: 0.9 }, version_label: "2026-jul", valid_from: "2026-07-01" },
      { value: { rate: 1 }, version_label: "2027", valid_from: "2027-07-01" },
    ],
  },
  {
    parameter: {
      key: "horario_jornada_diurna",
      name: "Horario jornada diurna",
      description: "Tramo horario diurno.",
      value_type: "json",
      is_global: true,
      can_company_override: true,
    },
    versions: [
      {
        value: { start: "06:00", end: "21:00" } as Json,
        version_label: "2026",
        valid_from: "2026-01-01",
      },
    ],
  },
  {
    parameter: {
      key: "horario_jornada_nocturna",
      name: "Horario jornada nocturna",
      description: "Inicio de la jornada nocturna.",
      value_type: "json",
      is_global: true,
      can_company_override: true,
    },
    versions: [
      {
        value: { start: "21:00" } as Json,
        version_label: "2026",
        valid_from: "2026-01-01",
      },
    ],
  },
  {
    parameter: {
      key: "topes_horas_extras",
      name: "Topes horas extras",
      description: "Tope operativo configurable.",
      value_type: "json",
      is_global: true,
      can_company_override: true,
    },
    versions: [
      {
        value: { daily_max: 2, weekly_max: 12, monthly_warning: 48 } as Json,
        version_label: "2026",
        valid_from: "2026-01-01",
      },
    ],
  },
];

export const CUSTOM_SETUP_STEPS = [
  "jornada laboral",
  "horas extras y recargos",
  "seguridad social",
  "parafiscales",
  "prestaciones",
  "bonificaciones",
  "comisiones",
  "incapacidades",
  "vacaciones",
  "faltas",
  "auxilio transporte",
  "cargos y áreas",
  "revisión final",
];
